var projects =[{  
      name:"Name2",
      thumbnail:"assets/images/portfolio_01.jpg",
      description:"",
      image:"",
      liveLink:"",
      category:"webdesign"
   },
   {  
      name:"Name1",
      thumbnail:"assets/images/portfolio_01.jpg",
      description:"",
      image:"",
      liveLink:"",
      category:"logo"
   },
   {  
      name:"Name3",
      thumbnail:"assets/images/portfolio_01.jpg",
      description:"",
      image:"",
      liveLink:"",
      category:"webdesign"
   },
   {  
      name:"Name4",
      thumbnail:"assets/images/portfolio_01.jpg",
      description:"",
      image:"",
      liveLink:"",
      category:"webdesign"
   },
   {  
      name:"Name5",
      thumbnail:"assets/images/portfolio_01.jpg",
      description:"",
      image:"",
      liveLink:"",
      category:"webdesign"
   },
   {  
      name:"Name6",
      thumbnail:"assets/images/portfolio_01.jpg",
      description:"",
      image:"",
      liveLink:"",
      category:"webdesign"
   }
];